controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# More modern way is to use PHP 8 attributes
# app_index:
#     path: /
#     controller: App\Controller\HelloController::index
